(() => {
const cfg=window.MOT_CONFIG||{}, configured=cfg.SUPABASE_PUBLISHABLE_KEY&&!cfg.SUPABASE_PUBLISHABLE_KEY.startsWith('YOUR_');
const sb=configured?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY):null;
const app=document.querySelector('#app');
let state={tab:sessionStorage.getItem('mot-crm-tab')||'dashboard',services:[],inquiries:[],categories:[]};
let siteSettings={}; let started=false; let booting=false;

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const imageExt=file=>(file?.name?.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';
const remoteImage=url=>/^https?:\/\//i.test(String(url||''))?String(url):'';
const currentLogo=()=>remoteImage(siteSettings?.logo_url);
const imgFallback=(url,alt,cls='thumb')=>{const src=remoteImage(url)||currentLogo();return `<img class="${cls}" src="${esc(src)}" alt="${esc(alt)}" data-fallback-logo="${esc(currentLogo())}" onerror="this.onerror=null;const f=this.dataset.fallbackLogo;if(f&&this.src!==f)this.src=f;else this.classList.add('image-unavailable');">`;};

function banner(message,type='success'){
 let host=document.querySelector('#crmBanners');
 if(!host){host=document.createElement('div');host.id='crmBanners';host.className='crm-banners';document.body.appendChild(host);}
 const el=document.createElement('div');el.className=`crm-banner ${type}`;el.innerHTML=`<span class="banner-dot"></span><span>${esc(message)}</span><button type="button" aria-label="Dismiss">×</button>`;host.appendChild(el);
 const remove=()=>{el.classList.add('leaving');setTimeout(()=>el.remove(),180)};el.querySelector('button').onclick=remove;setTimeout(remove,4200);
}
const success=m=>banner(m,'success'), errorBanner=m=>banner(m,'error'), infoBanner=m=>banner(m,'info');

async function loadPublicSettings(){if(!sb)return;const {data}=await sb.from('site_settings').select('*').eq('id',1).maybeSingle();if(data){siteSettings=data;const logo=currentLogo();const favicon=document.querySelector('link[rel="icon"]');if(favicon&&logo)favicon.href=logo;}}

async function login(){
 await loadPublicSettings(); const logo=currentLogo();
 app.innerHTML=`<div class="login"><div class="loginbox">${logo?imgFallback(logo,'Moments On Time','crm-login-logo'):''}<h2 style="text-align:center;margin-bottom:8px">Moments On Time CRM</h2><p class="small" style="text-align:center;margin-bottom:20px">Manage your services, categories, website settings and customer requests.</p>${!configured?`<div class="notice">Add the Supabase publishable/anon key in config.js before logging in.</div>`:''}<form id="loginForm"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="btn btn-primary">Sign in</button></form><p id="loginMsg" class="small" style="margin-top:14px"></p></div></div>`;
 document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const btn=e.currentTarget.querySelector('button');btn.disabled=true;btn.textContent='Signing in…';const o=Object.fromEntries(new FormData(e.currentTarget));const {error}=await sb.auth.signInWithPassword(o);if(error){document.querySelector('#loginMsg').textContent=error.message;btn.disabled=false;btn.textContent='Sign in';}else document.querySelector('#loginMsg').textContent='Signing in…';});
}

function shell(){
 app.innerHTML=`<div class="crm"><header class="crmbar"><a class="crmbrand" href="../">${currentLogo()?imgFallback(currentLogo(),'Moments On Time','crm-logo'):''}<span>Moments On Time CRM</span></a><div style="display:flex;align-items:center;gap:10px"><span id="userEmail" class="small"></span><button id="logout" class="btn-sm">Sign out</button></div></header><div class="crm-layout"><aside class="sidebar"><button class="sidebtn active" data-tab="dashboard">Dashboard</button><button class="sidebtn" data-tab="services">Services</button><button class="sidebtn" data-tab="categories">Categories</button><button class="sidebtn" data-tab="inquiries">Inquiries</button><button class="sidebtn" data-tab="settings">Site settings</button></aside><main id="main" class="main"></main></div></div>`;
 document.querySelector('#logout').onclick=async()=>{const btn=document.querySelector('#logout');btn.disabled=true;const {error}=await sb.auth.signOut();if(error){errorBanner(error.message);btn.disabled=false;} };
 document.querySelectorAll('.sidebtn').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;sessionStorage.setItem('mot-crm-tab',state.tab);document.querySelectorAll('.sidebtn').forEach(x=>x.classList.toggle('active',x===b));renderTab();});document.querySelectorAll('.sidebtn').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));
}
async function ensureAdmin(){
 const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data,error}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();
 if(error||!data){const logo=currentLogo();app.innerHTML=`<div class="login"><div class="loginbox">${logo?imgFallback(logo,'Moments On Time','crm-login-logo'):''}<h2>CRM access not enabled</h2><p class="small">Your Supabase Auth account exists, but its UUID is not in <code>admin_users</code>.</p><button class="btn btn-secondary" onclick="location.reload()">Retry</button></div></div>`;return false}return true;
}
async function refresh(){
 const [s,i,c]=await Promise.all([sb.from('services').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false}),sb.from('inquiries').select('*').order('created_at',{ascending:false}),sb.from('categories').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false})]);
 state.services=s.data||[];state.inquiries=i.data||[];state.categories=c.data||[];if(s.error)console.error(s.error);if(i.error)console.error(i.error);if(c.error)console.error(c.error);
}
function renderTab(){const m=document.querySelector('#main');if(!m)return;if(state.tab==='dashboard')renderDashboard(m);if(state.tab==='services')renderServices(m);if(state.tab==='categories')renderCategories(m);if(state.tab==='inquiries')renderInquiries(m);if(state.tab==='settings')renderSettings(m);}
function renderDashboard(m){
 const counts={new:0,contacted:0,approved:0,completed:0,cancelled:0};state.inquiries.forEach(x=>{const k=x.status||'new';if(counts[k]!==undefined)counts[k]++;});
 m.innerHTML=`<div class="toolbar"><div><div class="eyebrow">Overview</div><h2>Dashboard</h2></div></div><div class="stats stats-3"><div class="stat"><span>Services</span><b>${state.services.length}</b><span class="small">total catalogue items</span></div><div class="stat"><span>Categories</span><b>${state.categories.length}</b><span class="small">managed categories</span></div><div class="stat"><span>Total inquiries</span><b>${state.inquiries.length}</b><span class="small">all customer requests</span></div></div><div class="panel dashboard-status" style="margin-bottom:20px"><div class="section-mini-head"><div><div class="eyebrow">Inquiry tracking</div><h3>All inquiry statuses</h3></div><span class="small">Live overview of every request</span></div><div class="status-summary status-summary-5"><div class="summary-card new"><span>New</span><strong>${counts.new}</strong></div><div class="summary-card contacted"><span>Contacted</span><strong>${counts.contacted}</strong></div><div class="summary-card approved"><span>Approved</span><strong>${counts.approved}</strong></div><div class="summary-card completed"><span>Completed</span><strong>${counts.completed}</strong></div><div class="summary-card cancelled"><span>Cancelled</span><strong>${counts.cancelled}</strong></div></div></div>`;
}
function serviceOrderForCategory(category,excludeId=''){const ids=state.services.filter(x=>String(x.category||'').trim().toLowerCase()===String(category||'').trim().toLowerCase()&&x.id!==excludeId).map(x=>Number(x.sort_order)||0);return ids.length?Math.max(...ids)+1:1;}
function renderServices(m){
 const cats=[...state.categories].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));
 m.innerHTML=`<div class="toolbar"><div><div class="eyebrow">Catalogue</div><h2>Services</h2></div><button id="newService" class="btn btn-primary">+ Add service</button></div><div class="panel service-toolbar"><div class="search-wrap"><span class="search-icon">⌕</span><input id="serviceSearch" class="search-input" type="search" placeholder="Search services..."></div><select id="serviceCategoryFilter" class="filter-select"><option value="all">All categories</option>${cats.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('')}</select><select id="serviceActiveFilter" class="filter-select"><option value="all">All visibility</option><option value="active">Active only</option><option value="inactive">Inactive only</option></select></div><div class="panel"><div class="tablewrap"><table class="table"><thead><tr><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Visibility</th><th></th></tr></thead><tbody id="serviceRows"></tbody></table></div></div><div id="serviceModal" class="modal-backdrop"></div>`;
 const renderRows=()=>{const q=(document.querySelector('#serviceSearch')?.value||'').toLowerCase();const cf=document.querySelector('#serviceCategoryFilter')?.value||'all';const af=document.querySelector('#serviceActiveFilter')?.value||'all';const rows=state.services.filter(s=>(!q||[s.name,s.description,s.category].join(' ').toLowerCase().includes(q))&&(cf==='all'||s.category===cf)&&(af==='all'||(af==='active'?s.is_active:!s.is_active)));document.querySelector('#serviceRows').innerHTML=rows.length?rows.map(s=>`<tr><td>${imgFallback(s.image_url,s.name)}</td><td><b>${esc(s.name)}</b><div class="small">${esc(s.description||'')}</div></td><td>${esc(s.category)}</td><td>${s.price==null?'—':formatPrice(s.price)}</td><td><label class="switch"><input type="checkbox" class="service-visibility" data-id="${s.id}" ${s.is_active?'checked':''}><span class="slider"></span></label></td><td><div class="actions-sm"><button class="btn-sm edit" data-id="${s.id}">Edit</button><button class="btn-sm btn-danger del" data-id="${s.id}">Delete</button></div></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty-state"><strong>No services found</strong><span>Try another search or filter.</span></div></td></tr>`;document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>openServiceModal(state.services.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.del').forEach(b=>b.onclick=()=>deleteService(b.dataset.id));document.querySelectorAll('.service-visibility').forEach(ch=>ch.onchange=async()=>{const {error}=await sb.from('services').update({is_active:ch.checked}).eq('id',ch.dataset.id);if(error){ch.checked=!ch.checked;errorBanner(error.message);return;}const item=state.services.find(x=>x.id===ch.dataset.id);if(item)item.is_active=ch.checked;success(ch.checked?'Service is now visible.':'Service hidden from website.');});};
 ['serviceSearch','serviceCategoryFilter','serviceActiveFilter'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='serviceSearch'?'input':'change',renderRows));document.querySelector('#newService').onclick=()=>openServiceModal();renderRows();
}
function formatPrice(value){if(value===null||value===undefined||value==='')return '—';const n=Number(value);if(!Number.isFinite(n))return '—';return `${esc(siteSettings?.currency_symbol||'$')}${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
function openServiceModal(s=null){
 const modal=document.querySelector('#serviceModal');const cats=[...state.categories].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));const defaultCat=s?.category||cats[0]?.name||'';const order=s?Number(s.sort_order||1):serviceOrderForCategory(defaultCat);
 modal.innerHTML=`<div class="modal-card editor-modal"><div class="modal-head"><div><div class="eyebrow">Catalogue</div><h3>${s?'Edit service':'Add service'}</h3></div><button class="modal-close" id="closeServiceModal">×</button></div><form id="serviceForm"><input type="hidden" name="id" value="${esc(s?.id||'')}"><div class="grid2"><div class="field"><label>Name *</label><input name="name" required value="${esc(s?.name||'')}"></div><div class="field"><label>Category *</label><select name="category" required>${cats.length?cats.map(c=>`<option value="${esc(c.name)}" ${c.name===defaultCat?'selected':''}>${esc(c.name)}</option>`).join(''):'<option value="">Create a category first</option>'}</select></div><div class="field"><label>Price</label><input name="price" type="number" step="0.01" min="0" value="${esc(s?.price??'')}"></div><div class="field"><label>Service image</label><input id="serviceImage" name="image_file" type="file" accept="image/*"><div class="small">Stored in Supabase Storage. Max 6MB.</div></div><div class="field toggle-field"><label>Visibility</label><label class="switch"><input name="is_active" type="checkbox" ${s?.is_active!==false?'checked':''}><span class="slider"></span><span class="toggle-label">Visible on website</span></label></div></div>${s?.image_url?`<div class="image-editor"><img id="servicePreview" src="${esc(remoteImage(s.image_url)||currentLogo())}" data-fallback-logo="${esc(currentLogo())}" onerror="this.onerror=null;const f=this.dataset.fallbackLogo;if(f)this.src=f;else this.classList.add('image-unavailable');"><label class="small"><input id="removeServiceImage" type="checkbox"> Remove current image</label></div>`:''}<div class="field"><label>Description</label><textarea name="description">${esc(s?.description||'')}</textarea></div><div class="actions"><button class="btn btn-primary">${s?'Save changes':'Add service'}</button><button type="button" class="btn btn-secondary" id="cancelServiceModal">Cancel</button></div></form></div>`;
 modal.classList.add('open');
 const catSelect=document.querySelector('#serviceForm select[name="category"]');
 document.querySelector('#serviceImage').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){errorBanner('Please choose an image file.');e.target.value='';return;}if(f.size>6*1024*1024){errorBanner('Service images must be under 6MB.');e.target.value='';return;}const p=document.querySelector('#servicePreview');if(p)p.src=URL.createObjectURL(f);};
 const close=()=>{modal.classList.remove('open');};document.querySelector('#closeServiceModal').onclick=close;document.querySelector('#cancelServiceModal').onclick=close;modal.onclick=e=>{if(e.target===modal)close();};
 document.querySelector('#serviceForm').onsubmit=async e=>{e.preventDefault();await saveService(e.currentTarget,s,close);};
}
async function uploadFile(file,path){const {error}=await sb.storage.from('site-media').upload(path,file,{contentType:file.type,upsert:false,cacheControl:'3600'});if(error)throw error;const {data}=sb.storage.from('site-media').getPublicUrl(path);return data.publicUrl;}
async function removeStorage(path){if(!path)return;const {error}=await sb.storage.from('site-media').remove([path]);if(error)console.warn(error.message);}
async function normalizeServiceOrder(){
 const catRank=new Map([...state.categories].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map((c,i)=>[String(c.name).toLowerCase(),i]));
 const sorted=[...state.services].sort((a,b)=>{const ca=catRank.get(String(a.category||'').toLowerCase())??9999,cb=catRank.get(String(b.category||'').toLowerCase())??9999;if(ca!==cb)return ca-cb;return new Date(a.created_at)-new Date(b.created_at);});
 const updates=[];const perCat=new Map();for(const s of sorted){const k=String(s.category||'').toLowerCase();const next=(perCat.get(k)||0)+1;perCat.set(k,next);if(Number(s.sort_order)!==next)updates.push(sb.from('services').update({sort_order:next}).eq('id',s.id));}if(updates.length)await Promise.all(updates);
}
async function saveService(form,s,close){
 const o=Object.fromEntries(new FormData(form));const file=form.elements.image_file.files[0];const removeImage=document.querySelector('#removeServiceImage')?.checked;o.price=o.price===''?null:Number(o.price);o.is_active=form.elements.is_active.checked;delete o.id;delete o.image_file;delete o.sort_order;let newPath=null;
 try{if(!o.category)throw new Error('Please choose a category.');if(file){newPath=`services/${s?.id||crypto.randomUUID()}/${Date.now()}.${imageExt(file)}`;o.image_url=await uploadFile(file,newPath);o.image_storage_path=newPath;}else if(s&&removeImage){o.image_url=null;o.image_storage_path=null;}else{delete o.image_url;delete o.image_storage_path;}
   const q=s?sb.from('services').update(o).eq('id',s.id):sb.from('services').insert(o);const {error}=await q;if(error)throw error;if(s&&file&&s.image_storage_path)await removeStorage(s.image_storage_path);if(s&&removeImage&&!file&&s.image_storage_path)await removeStorage(s.image_storage_path);await refresh();await normalizeServiceOrder();await refresh();close();renderServices(document.querySelector('#main'));success(s?'Service updated successfully.':'Service added successfully.');
 }catch(err){if(newPath)await removeStorage(newPath);errorBanner(err.message||String(err));}
}
async function deleteService(id){if(!confirm('Delete this service and its stored image?'))return;const s=state.services.find(x=>x.id===id);const {error}=await sb.from('services').delete().eq('id',id);if(error){errorBanner(error.message);return;}if(s?.image_storage_path)await removeStorage(s.image_storage_path);await refresh();await normalizeServiceOrder();await refresh();renderServices(document.querySelector('#main'));success('Service deleted successfully.');}

function renderCategories(m){
 m.innerHTML=`<div class="toolbar"><div><div class="eyebrow">Website content</div><h2>Categories</h2></div><button id="newCategory" class="btn btn-primary">+ Add category</button></div><div class="panel service-toolbar"><div class="search-wrap"><span class="search-icon">⌕</span><input id="categorySearch" class="search-input" type="search" placeholder="Search categories..."></div><select id="categoryImageFilter" class="filter-select"><option value="all">All images</option><option value="has">Has image</option><option value="missing">Missing image</option></select><select id="categoryVisibilityFilter" class="filter-select"><option value="all">All visibility</option><option value="visible">Visible</option><option value="hidden">Hidden</option></select></div><div id="categoryGridCRM" class="crm-category-grid"></div><div id="categoryModal" class="modal-backdrop"></div>`;
 const renderGrid=()=>{const q=(document.querySelector('#categorySearch')?.value||'').toLowerCase();const im=document.querySelector('#categoryImageFilter')?.value||'all';const vf=document.querySelector('#categoryVisibilityFilter')?.value||'all';let rows=state.categories.filter(c=>(!q||String(c.name).toLowerCase().includes(q))&&(im==='all'||(im==='has'?!!c.image_url:!c.image_url))&&(vf==='all'||(vf==='visible'?c.is_visible!==false:c.is_visible===false)));rows.sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));document.querySelector('#categoryGridCRM').innerHTML=rows.length?rows.map(c=>`<article class="crm-category-card"><div class="crm-category-image">${imgFallback(c.image_url,c.name,'category-thumb')}<span class="category-visibility ${c.is_visible!==false?'visible':'hidden'}">${c.is_visible!==false?'Visible':'Hidden'}</span></div><div class="crm-category-body"><h3>${esc(c.name)}</h3><div class="category-actions"><label class="switch"><input type="checkbox" class="category-visibility-toggle" data-id="${c.id}" ${c.is_visible!==false?'checked':''}><span class="slider"></span></label><span class="small">Website visibility</span></div><div class="actions-sm"><button class="btn-sm edit-category" data-id="${c.id}">Edit</button><button class="btn-sm btn-danger delete-category" data-id="${c.id}">Delete</button></div></div></article>`).join(''):`<div class="empty-state" style="grid-column:1/-1"><strong>No categories found</strong><span>Add a category or change your filters.</span></div>`;document.querySelectorAll('.edit-category').forEach(b=>b.onclick=()=>openCategoryModal(state.categories.find(x=>x.id===b.dataset.id)));document.querySelectorAll('.delete-category').forEach(b=>b.onclick=()=>deleteCategory(b.dataset.id));document.querySelectorAll('.category-visibility-toggle').forEach(ch=>ch.onchange=async()=>{const id=ch.dataset.id;const visible=ch.checked;const {error}=await sb.from('categories').update({is_visible:visible}).eq('id',id);if(error){ch.checked=!visible;errorBanner(error.message);return;}const cat=state.categories.find(x=>x.id===id);if(cat)cat.is_visible=visible;if(!visible){const name=cat?.name;const related=state.services.filter(x=>String(x.category||'').trim().toLowerCase()===String(name||'').trim().toLowerCase());if(related.length)await Promise.all(related.map(x=>sb.from('services').update({is_active:false}).eq('id',x.id)));related.forEach(x=>x.is_active=false);success('Category hidden and related services removed from the website.');}else success('Category is visible again.');renderGrid();});};['categorySearch','categoryImageFilter','categoryVisibilityFilter'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='categorySearch'?'input':'change',renderGrid));document.querySelector('#newCategory').onclick=()=>openCategoryModal();renderGrid();
}
function openCategoryModal(c=null){
 const modal=document.querySelector('#categoryModal');const next=Math.max(0,...state.categories.map(x=>Number(x.sort_order)||0))+1;modal.innerHTML=`<div class="modal-card editor-modal"><div class="modal-head"><div><div class="eyebrow">Website content</div><h3>${c?'Edit category':'Add category'}</h3></div><button class="modal-close" id="closeCategoryModal">×</button></div><form id="categoryForm"><div class="grid2"><div class="field"><label>Name *</label><input name="name" required value="${esc(c?.name||'')}"></div><div class="field toggle-field"><label>Visibility</label><label class="switch"><input name="is_visible" type="checkbox" ${c?.is_visible!==false?'checked':''}><span class="slider"></span><span class="toggle-label">Visible on website</span></label></div></div><div class="field"><label>Category image</label><input id="categoryImage" name="image_file" type="file" accept="image/*"><div class="small">Upload a clear category image.</div></div>${c?.image_url?`<div class="image-editor"><img id="categoryPreview" src="${esc(remoteImage(c.image_url)||currentLogo())}" data-fallback-logo="${esc(currentLogo())}" onerror="this.onerror=null;const f=this.dataset.fallbackLogo;if(f)this.src=f;else this.classList.add('image-unavailable');"><label class="small"><input id="removeCategoryImage" type="checkbox"> Remove current image</label></div>`:''}<div class="actions"><button class="btn btn-primary">${c?'Save changes':'Add category'}</button><button type="button" class="btn btn-secondary" id="cancelCategoryModal">Cancel</button></div></form></div>`;modal.classList.add('open');const file=document.querySelector('#categoryImage');file.onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){errorBanner('Please choose an image file.');e.target.value='';return;}if(f.size>6*1024*1024){errorBanner('Category images must be under 6MB.');e.target.value='';return;}const p=document.querySelector('#categoryPreview');if(p)p.src=URL.createObjectURL(f);};const close=()=>modal.classList.remove('open');document.querySelector('#closeCategoryModal').onclick=close;document.querySelector('#cancelCategoryModal').onclick=close;modal.onclick=e=>{if(e.target===modal)close();};document.querySelector('#categoryForm').onsubmit=async e=>{e.preventDefault();await saveCategory(e.currentTarget,c,close);};
}
async function saveCategory(form,c,close){const name=form.elements.name.value.trim();const order=c?Number(c.sort_order||1):Math.max(1,...state.categories.map(x=>Number(x.sort_order)||0))+1;const visible=form.elements.is_visible.checked;const file=document.querySelector('#categoryImage').files[0];const removeImage=document.querySelector('#removeCategoryImage')?.checked;if(!name){errorBanner('Category name is required.');return;}const duplicate=state.categories.find(x=>x.name.trim().toLowerCase()===name.toLowerCase()&&x.id!==c?.id);if(duplicate){errorBanner('A category with this name already exists.');return;}let path=null;try{const payload={name,sort_order:order,is_visible:visible};if(file){path=`categories/${slug(name)}/${Date.now()}.${imageExt(file)}`;payload.image_url=await uploadFile(file,path);payload.storage_path=path;}else if(c&&removeImage){payload.image_url=null;payload.storage_path=null;}const {error}=c?await sb.from('categories').update(payload).eq('id',c.id):await sb.from('categories').insert(payload);if(error)throw error;if(c&&c.name.trim().toLowerCase()!==name.toLowerCase()){const moved=await sb.from('services').update({category:name}).eq('category',c.name);if(moved.error)throw moved.error;}if(!visible){const related=state.services.filter(x=>String(x.category||'').trim().toLowerCase()===name.toLowerCase());if(related.length)await Promise.all(related.map(x=>sb.from('services').update({is_active:false}).eq('id',x.id)));}if(c&&file&&c.storage_path)await removeStorage(c.storage_path);if(c&&removeImage&&!file&&c.storage_path)await removeStorage(c.storage_path);await refresh();await normalizeServiceOrder();await refresh();close();renderCategories(document.querySelector('#main'));success(c?'Category updated successfully.':'Category added successfully.');}catch(err){if(path)await removeStorage(path);errorBanner(err.message||String(err));}}
async function deleteCategory(id){const c=state.categories.find(x=>x.id===id);if(!c)return;if(state.services.some(s=>String(s.category||'').toLowerCase()===String(c.name||'').toLowerCase())){errorBanner('This category is used by one or more services. Change those services before deleting it.');return;}if(!confirm(`Delete the category “${c.name}” and its image?`))return;const {error}=await sb.from('categories').delete().eq('id',id);if(error){errorBanner(error.message);return;}if(c.storage_path)await removeStorage(c.storage_path);await refresh();await normalizeServiceOrder();await refresh();renderCategories(document.querySelector('#main'));success('Category deleted successfully.');}

function renderInquiries(m){
 const statuses=['new','contacted','approved','completed','cancelled'];const labels={new:'New',contacted:'Contacted',approved:'Approved',completed:'Completed',cancelled:'Cancelled'};
 m.innerHTML=`<div class="toolbar"><div><div class="eyebrow">Customer requests</div><h2>Inquiries</h2></div><span id="inquiryCount" class="results-count"></span></div><div class="panel inquiry-tools"><div class="search-wrap"><span class="search-icon">⌕</span><input id="inquirySearch" class="search-input" type="search" placeholder="Search name, phone, email, service, message or note..."></div><div class="filter-wrap"><label for="inquiryStatusFilter">Status</label><select id="inquiryStatusFilter" class="filter-select"><option value="all">All statuses</option>${statuses.map(v=>`<option value="${v}">${labels[v]}</option>`).join('')}</select></div></div><div class="panel"><div class="tablewrap"><table class="table inquiry-table"><thead><tr><th>Inquiry #</th><th>Date</th><th>Customer</th><th>Phone</th><th>Service</th><th>Message</th><th>Status</th><th></th></tr></thead><tbody id="inquiryRows"></tbody></table></div></div><div id="inquiryModal" class="modal-backdrop"></div>`;
 const renderRows=()=>{const q=(document.querySelector('#inquirySearch')?.value||'').trim().toLowerCase();const filter=document.querySelector('#inquiryStatusFilter')?.value||'all';const rows=state.inquiries.filter(x=>{const hay=[x.name,x.email,x.phone,x.service,x.message,x.notes,x.status].map(v=>String(v??'').toLowerCase()).join(' ');return(!q||hay.includes(q))&&(filter==='all'||x.status===filter);});document.querySelector('#inquiryRows').innerHTML=rows.length?rows.map(x=>`<tr><td><strong class="detail-id">${esc(x.inquiry_number||'—')}</strong></td><td><div class="date-main">${esc(formatDate(x.created_at))}</div></td><td><b>${esc(x.name||'—')}</b><div class="small">${esc(x.email||'No email')}</div></td><td>${esc(x.phone||'—')}</td><td>${esc(x.service||'—')}</td><td><span class="message-preview">${esc(x.message||'—')}</span></td><td><select class="status-select ${statusClass(x.status||'new')}" data-id="${esc(x.id)}">${statuses.map(v=>`<option value="${v}" ${x.status===v?'selected':''}>${labels[v]}</option>`).join('')}</select></td><td><button class="btn-sm btn-view view-inquiry" data-id="${esc(x.id)}">View</button></td></tr>`).join(''):`<tr><td colspan="8"><div class="empty-state"><strong>No inquiries found</strong><span>Try changing the search or filter.</span></div></td></tr>`;document.querySelector('#inquiryCount').textContent=`${rows.length} ${rows.length===1?'inquiry':'inquiries'}`;document.querySelectorAll('.status-select').forEach(select=>select.onchange=async()=>{const value=select.value,id=select.dataset.id;select.className=`status-select ${statusClass(value)}`;const {error}=await sb.from('inquiries').update({status:value}).eq('id',id);if(error){errorBanner(error.message);await refresh();renderInquiries(document.querySelector('#main'));return;}const item=state.inquiries.find(x=>x.id===id);if(item)item.status=value;success('Inquiry status updated.');});document.querySelectorAll('.view-inquiry').forEach(b=>b.onclick=()=>openInquiryModal(state.inquiries.find(x=>x.id===b.dataset.id)));};
 document.querySelector('#inquirySearch').oninput=renderRows;document.querySelector('#inquiryStatusFilter').onchange=renderRows;renderRows();
}
function formatDate(v){try{return new Date(v).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}catch{return v||'—';}}
function statusClass(v){return `status-${esc(v)}`;}
function openInquiryModal(x){
 if(!x)return;const modal=document.querySelector('#inquiryModal');const labels={new:'New',contacted:'Contacted',approved:'Approved',completed:'Completed',cancelled:'Cancelled'};const status=x.status||'new';
 modal.innerHTML=`<div class="modal-card inquiry-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><div class="eyebrow">Customer inquiry</div><h3>${esc(x.name||'Inquiry details')}</h3></div><button class="modal-close" id="closeInquiryModal">×</button></div><div class="inquiry-detail-grid"><div class="detail-item"><span>Submitted</span><strong>${esc(formatDate(x.created_at))}</strong></div><div class="detail-item"><span>Status</span><strong><span class="status-badge status-${esc(status)}">${esc(labels[status]||status)}</span></strong></div><div class="detail-item"><span>Phone / WhatsApp</span><strong>${esc(x.phone||'—')}</strong></div><div class="detail-item"><span>Email</span><strong>${esc(x.email||'—')}</strong></div><div class="detail-item"><span>Service</span><strong>${esc(x.service||'—')}</strong></div><div class="detail-item"><span>Inquiry number</span><strong class="detail-id">${esc(x.inquiry_number||x.id||'—')}</strong></div></div><div class="detail-message"><span>Customer message</span><p>${esc(x.message||'No message provided.')}</p></div><div class="note-box"><div class="note-head"><div><span>Internal note</span><small>Only visible inside your CRM.</small></div></div><textarea id="inquiryNote" placeholder="Add a note about this customer or follow-up…">${esc(x.notes||'')}</textarea><div class="actions"><button class="btn btn-primary" id="saveInquiryNote">Save note</button></div></div></div>`;
 modal.classList.add('open');const close=()=>modal.classList.remove('open');document.querySelector('#closeInquiryModal').onclick=close;modal.onclick=e=>{if(e.target===modal)close();};document.querySelector('#saveInquiryNote').onclick=async()=>{const btn=document.querySelector('#saveInquiryNote');const notes=document.querySelector('#inquiryNote').value.trim();btn.disabled=true;const {error}=await sb.from('inquiries').update({notes}).eq('id',x.id);if(error){errorBanner(error.message);btn.disabled=false;return;}x.notes=notes;const item=state.inquiries.find(i=>i.id===x.id);if(item)item.notes=notes;success('Internal note saved.');btn.textContent='Saved';setTimeout(()=>{btn.disabled=false;btn.textContent='Save note';},1000);};
}

async function renderSettings(m){
 const {data:s,error}=await sb.from('site_settings').select('*').eq('id',1).maybeSingle();if(error)console.error(error);siteSettings=s||siteSettings;
 const textFields=[['brand_name','Brand name'],['nav_categories','Navigation: Categories'],['nav_services','Navigation: Collection'],['nav_about','Navigation: About'],['nav_contact','Navigation: Contact'],['nav_cta','Navigation button'],['hero_eyebrow','Hero eyebrow'],['hero_title','Hero title'],['hero_text','Hero text'],['hero_primary_cta','Hero primary button'],['hero_secondary_cta','Hero secondary button'],['categories_eyebrow','Categories eyebrow'],['categories_title','Categories title'],['categories_intro','Categories intro'],['category_more_label','Category more button'],['services_eyebrow','Services eyebrow'],['services_title','Services title'],['services_intro','Services intro'],['service_more_label','Service more button'],['about_eyebrow','About eyebrow'],['about_title','About title'],['about_quote','About quote'],['about_text','About text'],['contact_eyebrow','Contact eyebrow'],['contact_title','Contact title'],['contact_intro','Contact intro'],['contact_side_text','Contact side text'],['form_name_label','Form: Name label'],['form_phone_label','Form: Phone label'],['form_email_label','Form: Email label'],['form_service_label','Form: Service label'],['form_message_label','Form: Message label'],['form_service_placeholder','Form: Service placeholder'],['form_message_placeholder','Form: Message placeholder'],['form_submit','Form: Submit button']];
 m.innerHTML=`<div class="toolbar"><div><div class="eyebrow">Website</div><h2>Site settings</h2></div></div><div class="panel"><form id="settingsForm"><div class="grid2"><div class="field"><label>Instagram URL</label><input name="instagram_url" value="${esc(s?.instagram_url||cfg.INSTAGRAM_URL||'')}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(s?.phone||'')}"></div><div class="field"><label>WhatsApp</label><input name="whatsapp" value="${esc(s?.whatsapp||'')}"></div><div class="field"><label>Email</label><input name="email" type="email" value="${esc(s?.email||'')}"></div><div class="field"><label>Currency symbol</label><input name="currency_symbol" value="${esc(s?.currency_symbol||'$')}" maxlength="8"></div><div class="field"><label>Categories shown at a time</label><input name="category_limit" type="number" min="1" step="1" value="${esc(s?.category_limit||4)}"></div><div class="field"><label>Services shown at a time</label><input name="service_limit" type="number" min="1" step="1" value="${esc(s?.service_limit||4)}"></div></div><div class="section-label">Website text</div><div class="text-settings-grid">${textFields.map(([n,l])=>`<div class="field"><label>${l}</label>${['hero_text','categories_intro','services_intro','about_quote','about_text','contact_intro','contact_side_text'].includes(n)?`<textarea name="${n}">${esc(s?.[n]||'')}</textarea>`:`<input name="${n}" value="${esc(s?.[n]||'')}">`}</div>`).join('')}</div><div class="section-label">Branding</div><div class="field"><label>Website logo</label><input id="logoFile" type="file" accept="image/*"><div class="small">Upload or replace your website logo.</div></div><div class="image-editor"><img id="logoPreview" src="${esc(remoteImage(s?.logo_url)||currentLogo())}" data-fallback-logo="${esc(currentLogo())}" onerror="this.onerror=null;const f=this.dataset.fallbackLogo;if(f)this.src=f;else this.classList.add('image-unavailable');" alt="Logo preview"><div class="actions"><button type="button" class="btn-sm btn-danger" id="deleteLogo" ${s?.logo_url?'':'disabled'}>Delete logo</button></div></div><div class="actions"><button class="btn btn-primary">Save settings</button></div></form></div>`;
 const file=document.querySelector('#logoFile');file.onchange=()=>{const f=file.files[0];if(!f)return;if(!f.type.startsWith('image/')){errorBanner('Please choose an image file.');file.value='';return;}if(f.size>6*1024*1024){errorBanner('Logo must be under 6MB.');file.value='';return;}document.querySelector('#logoPreview').src=URL.createObjectURL(f);};
 document.querySelector('#deleteLogo').onclick=async()=>{if(!s?.logo_url)return;if(!confirm('Delete the website logo?'))return;try{if(s.logo_storage_path)await removeStorage(s.logo_storage_path);const {error}=await sb.from('site_settings').update({logo_url:null,logo_storage_path:null}).eq('id',1);if(error)throw error;siteSettings={...siteSettings,logo_url:null,logo_storage_path:null};await loadPublicSettings();renderSettings(document.querySelector('#main'));success('Logo deleted successfully.');}catch(err){errorBanner(err.message||String(err));}};
 document.querySelector('#settingsForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.currentTarget));const logoFile=file.files[0];let newPath=null;try{delete o.currency_code;o.category_limit=Math.max(1,Number(o.category_limit)||4);o.service_limit=Math.max(1,Number(o.service_limit)||4);if(logoFile){newPath=`branding/logo-${Date.now()}.${imageExt(logoFile)}`;o.logo_url=await uploadFile(logoFile,newPath);o.logo_storage_path=newPath;}else{delete o.logo_url;delete o.logo_storage_path;}const {error}=await sb.from('site_settings').update(o).eq('id',1);if(error)throw error;if(logoFile&&s?.logo_storage_path)await removeStorage(s.logo_storage_path);await loadPublicSettings();success('Settings saved successfully.');renderSettings(document.querySelector('#main'));}catch(err){if(newPath)await removeStorage(newPath);errorBanner(err.message||String(err));}};
}
async function start(){
 if(started||booting)return;booting=true;try{if(!sb){await login();return;}const {data:{session}}=await sb.auth.getSession();if(!session){await login();return;}if(!(await ensureAdmin()))return;await loadPublicSettings();shell();document.querySelector('#userEmail').textContent=session.user.email||'';await refresh();renderTab();started=true;}finally{booting=false;}}

sb?.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){started=false;setTimeout(()=>login(),0);}else if(event==='SIGNED_IN'&&!started){setTimeout(()=>start(),0);}});
start();
})();
